version: '3'
services:
  web:
    build: ./demo/
    ports:
      - "8082:8082"
    depends_on:
      - janus
      - janus-node
  janus-node:      
    image: "janus-node"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - janus
    environment:
      JANUS_NODE_SERVER_ADDRESS: "ws://janus:8090"
      JANUS_NODE_WS_PORT: 8080
      JANUS_NODE_HTTP_PORT: 8081
  janus:
    image: "janus.fat"
    env_file: ./janus/.env
    ports:
      - "7088:7088"
      - "8090:8090"
